version: '3.8'
services:
  backend:
    build: ./AuthApp
    ports:
      - "5000:5000"
    env_file:
      - ./AuthApp/.env
    restart: always
    labels:
      - "netdata.enable=true"
      - "netdata.service=backend"
  
  frontend:
    build: ./netflix
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: always
    labels:
      - "netdata.enable=true"
      - "netdata.service=frontend"
  
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    hostname: netdata-docker
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: always
    environment:
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN:-}
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS:-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - NETDATA_EXTRA_DEB_PACKAGES=curl
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - default
    depends_on:
      - backend
      - frontend

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
